Issue923 theme hook
Workday/canvas-kit pull request #2120
Opened 2023-03-29 16:45 UTC by RayRedGoose

## Summary

Fixes: #1234 

## Release Category
Components

### Release Note
Optional release note message. Changelog and release summaries will contain a pull request title. This section will add additional notes under that title. This section is not a summary, but something extra to point out in release notes. An example might be calling out breaking changes in a labs component or minor visual changes that need visual regression updates. Remove this section if no additional release notes are required.

### BREAKING CHANGES
Optional breaking changes message. If your PR includes breaking changes. It is extremely rare to put breaking changes outside a `prerelease/major` branch. Anything in this section will show up in release notes. Remove this section if no breaking changes are present.

---

## Checklist

- [ ] MDX documentation adheres to Canvas Kit's [standard MDX template](https://github.com/Workday/canvas-kit/discussions/1131)
- [ ] Label `ready for review` has been added to PR

## For the Reviewer

- [ ] PR title is short and descriptive
- [ ] PR summary describes the change (Fixes/Resolves linked correctly)
- [ ] PR Release Notes describes additional information useful to call out in a release message or removed if not applicable
- [ ] Breaking Changes provides useful information to upgrade to this code or removed if not applicable

## Where Should the Reviewer Start?

## Areas for Feedback? (optional)

- [ ] Code
- [ ] Documentation
- [ ] Testing
- [ ] Codemods

## Testing Manually

## Screenshots or GIFs (if applicable)

## Thank You Gif (optional)

2023-03-30 19:38 UTC, mannycarrera4 commented
Heads up, I believe we have a `getCanvasTheme` that looks like its doing similar work to `getTheme`. 
We should keep the validation in `useTheme` but should we deprecate it?

2023-03-31 16:20 UTC, NicholasBoll commented
The contents of `getTheme` and `useTheme` were not what I expected. They contain duplicate implementations. I was thinking `useTheme` made calls to `getTheme` instead of containing duplicated functionality.

2023-04-04 22:06 UTC, alanbsmith requested changes
The code for this looks good. Thanks, Raisa. 😄 I'd like to tweak the documentation a bit more to help users understand how these four functions are different and when they should choose which option.

2023-04-04 22:06 UTC, alanbsmith commented on modules/react/common/lib/theming/README.md
> +
I think we want something more like this: `getCanvasTheme` and `useCanvasTheme` use a Proxy, so you trade completeness for performance. If you only need the last property in a member expression, these are a good option.

2023-04-06 16:04 UTC, mannycarrera4 commented on modules/react/common/lib/theming/index.ts
>  export * from './getObjectProxy';
do we still need objectProxy?  i know this was used for get canvas theme

2023-04-06 16:05 UTC, mannycarrera4 commented on modules/react/common/lib/theming/useTheme.ts
> +          'useTheme: Context not supported or invalid. Please consider to use `getTheme` function instead for `styled` or class components.'
```suggestion
          'useTheme: Context not supported or invalid. Please consider to using `getTheme` function instead for `styled` or class components.'
```

2023-04-06 16:09 UTC, mannycarrera4 commented
Code wise this looks good to me! I'll let someone else take a look at the docs! 👍

2023-04-06 18:59 UTC, alanbsmith approved these changes
Looks great, Raisa. I made some documentation nits, but overall, this looks good.

2023-04-06 18:59 UTC, alanbsmith commented on modules/react/common/lib/theming/README.md
> +the canvas key.
```suggestion
`getTheme` is a function that returns the full theme object with the Canvas Kit theme under the `canvas` key. It should be used with `styled` components, class components, or outside components.
```

2023-04-06 18:59 UTC, alanbsmith commented on modules/react/common/lib/theming/README.md
> +**Example**
```suggestion
Below is an example of how to use `getTheme` to build responsive media query styles with the breakpoint functions provided in the theme.
```

2023-04-06 18:59 UTC, alanbsmith commented on modules/react/common/lib/theming/README.md
> +**Example**
```suggestion
Below is an example showing how to use `useTheme` in a function component to set `Subtext`'s color to the error color provided by the theme.
```

2023-04-06 18:59 UTC, alanbsmith commented on modules/react/common/lib/theming/README.md
> +
Let's remove this and add it to the top to remove duplication. 😄
```suggestion
```

2023-04-06 18:59 UTC, alanbsmith commented on modules/react/common/lib/theming/README.md
> +
Let's remove this and add it to the top to remove duplication. 😄
```suggestion
```

2023-04-06 18:59 UTC, alanbsmith commented on modules/react/common/lib/theming/useTheme.ts
> + */
This is really nice JSDoc. Thank you. 😄

2023-04-06 18:59 UTC, alanbsmith commented on modules/react/common/lib/theming/useTheme.ts
> + * }
Same here. I love all this detail. It's very clear and readable.

2023-04-06 20:54 UTC, mannycarrera4 commented on modules/docs/mdx/9.0-UPGRADE-GUIDE.mdx
> +- [Token Updates](#token-updates) - [Depth](#depth)
can you update this, it happens to me all the time

2023-04-07 17:02 UTC, mannycarrera4 approved these changes

2023-04-07 17:03 UTC, mannycarrera4 commented on modules/docs/mdx/9.0-UPGRADE-GUIDE.mdx
> +`useCanvasTheme` and `getCanvasTheme` have been removed as it's can be safely replaced by `useTheme`
```suggestion
`useCanvasTheme` and `getCanvasTheme` have been removed as they can be safely replaced by `useTheme`
```

2023-04-07 17:05 UTC, mannycarrera4 commented on modules/docs/mdx/9.0-UPGRADE-GUIDE.mdx
> +and `getTheme` and there is no external usage of this functions found.
```suggestion
and `getTheme`.
```

2023-04-07 17:05 UTC, mannycarrera4 commented on modules/docs/mdx/9.0-UPGRADE-GUIDE.mdx
> +`useCanvasTheme` and `getCanvasTheme` have been removed as it's can be safely replaced by `useTheme`
```suggestion
`useCanvasTheme` and `getCanvasTheme` have been removed and can be safely replaced by `useTheme`
```

2023-04-07 17:06 UTC, mannycarrera4 approved these changes

2023-04-07 17:16 UTC, merged