fix: Changing ARIA role to switch
Workday/canvas-kit pull request #2292
Opened 2023-07-18 18:44 UTC by bstanton678

Additionally, removing tabindex attribute. Didn't seem necessary when the input element is already in focus order anyway.

## Summary

Fixes: No bug reported. 

Contributing updates to the accessibility guidelines on the Canvas Kit design site, I noticed the Switch component rendered with an ARIA checkbox role. This didn't seem appropriate for the Switch component. 

## Release Category
Components

### Release Note
Optional release note message. Changelog and release summaries will contain a pull request title. This section will add additional notes under that title. This section is not a summary, but something extra to point out in release notes. An example might be calling out breaking changes in a labs component or minor visual changes that need visual regression updates. Remove this section if no additional release notes are required.

### BREAKING CHANGES
Optional breaking changes message. If your PR includes breaking changes. It is extremely rare to put breaking changes outside a `prerelease/major` branch. Anything in this section will show up in release notes. Remove this section if no breaking changes are present.

---

## Checklist

- [ ] MDX documentation adheres to Canvas Kit's [standard MDX template](https://github.com/Workday/canvas-kit/discussions/1131)
- [ ] Label `ready for review` has been added to PR

## For the Reviewer

- [ ] PR title is short and descriptive
- [ ] PR summary describes the change (Fixes/Resolves linked correctly)
- [ ] PR Release Notes describes additional information useful to call out in a release message or removed if not applicable
- [ ] Breaking Changes provides useful information to upgrade to this code or removed if not applicable

## Where Should the Reviewer Start?

`/modules/react/switch/lib`

## Areas for Feedback? (optional)

- [ ] Code
- [ ] Documentation
- [ ] Testing
- [ ] Codemods

## Testing Manually

1. Make sure the Switch component still appears in keyboard focus order, 
2. Make sure the Switch component still responds to the Space bar and changing state, 
3. Validate screen readers are describing the component's role as "switch"
4. Validate screen readers are describing the state of "on" or "off"

## Screenshots or GIFs (if applicable)

ARIA roles do not have any impact on the visual UI. 

## Thank You Gif (optional)

2023-07-19 17:48 UTC, alanbsmith approved these changes

2023-07-19 17:50 UTC, alanbsmith requested changes
Looks like the test also needs to be updated. I [submitted a PR](https://github.com/bstanton678/canvas-kit/pull/8) to your PR branch. You can merge that into your branch or just make a tweak [here](https://github.com/Workday/canvas-kit/blob/master/cypress/integration/Switch.spec.ts#L4) and push it up. 😄 Thanks for the fix!

2023-07-25 21:29 UTC, alanbsmith approved these changes

2023-07-25 21:29 UTC, mannycarrera4 approved these changes

2023-07-25 21:29 UTC, merged