chore: Add versions mdx
Workday/canvas-kit pull request #2553
Opened 2024-02-06 21:56 UTC by mannycarrera4

## Summary

Fixes: https://github.com/Workday/canvas-kit/issues/2521

## Release Category
Documentation

### Release Note
We've added a table of previous versions to storybook

---

## Checklist

- [ ] MDX documentation adheres to Canvas Kit's [Documentation Guidelines](https://workday.github.io/canvas-kit/?path=/docs/guides-documentation-guidelines--page)
- [ ] Label `ready for review` has been added to PR

## For the Reviewer

- [ ] PR title is short and descriptive
- [ ] PR summary describes the change (Fixes/Resolves linked correctly)
- [ ] PR Release Notes describes additional information useful to call out in a release message or removed if not applicable
- [ ] Breaking Changes provides useful information to upgrade to this code or removed if not applicable

## Where Should the Reviewer Start?

## Areas for Feedback? (optional)

- [ ] Code
- [ ] Documentation
- [ ] Testing
- [ ] Codemods

## Testing Manually

## Screenshots or GIFs (if applicable)

## Thank You Gif (optional)

2024-02-07 23:04 UTC, alanbsmith commented on modules/docs/mdx/Versions.mdx
> +    documentation: 'https://d2krrudi3mmzzw.cloudfront.net/v9/?path=/docs/welcome--page',
Are these urls stable?

2024-02-07 23:40 UTC, alanbsmith requested changes
Thanks for working on this. I suggested some changes. 😄

2024-02-07 23:40 UTC, alanbsmith commented on modules/docs/mdx/Versions.mdx
> +      if (item.versionNumber === version) {
Question: Why don't you need to parse the version string here?

2024-02-07 23:40 UTC, alanbsmith commented on modules/docs/mdx/Versions.mdx
> +
```suggestion
const statusIndicators = {
  stable: {
    variant: 'blue',
    label: 'Stable',
  },
    support: {
    variant: 'green',
    label: 'Support',
  },
    deprecated: {
    variant: 'red',
    label: 'No Longer Supported',
  }
};

function getVersionStatusIndicator(versionNumber: number) {
  const currentMajorVersion = Number(version.split('.')[0]);
  // if this is the current version
  if (vesionNumber === currentMajorVersion) {
    return statusIndicators.stable;
  } else if (versionNumber === currentMajorVersion - 1) {
    return statusIndicators.support;
  } else {
    return statusIndicators.deprecated;
  }
}
```

2024-02-07 23:40 UTC, alanbsmith commented on modules/docs/mdx/Versions.mdx
> +      if (item.versionNumber === version) {
`version` should be a string (I think), and `versionNumber` is a number. they'll never be equal.

2024-02-07 23:40 UTC, alanbsmith commented on modules/docs/mdx/Versions.mdx
> +      return (
Comment: I appreciate you trying to keep this all in one spot, but I think it's more readable if you split it out.

2024-02-07 23:40 UTC, alanbsmith commented on modules/docs/mdx/Versions.mdx
> +      }
```suggestion
    {allVersions.map(item => {
      const {label, variant} = getVersionStatusIndicator(item.version);
```

2024-02-07 23:40 UTC, alanbsmith commented on modules/docs/mdx/Versions.mdx
> +              <StatusIndicator.Label>{status}</StatusIndicator.Label>
```suggestion
            <StatusIndicator variant={variant.}>
              <StatusIndicator.Label>{label}</StatusIndicator.Label>
```

2024-02-08 15:16 UTC, mannycarrera4 commented on modules/docs/mdx/Versions.mdx
> +    documentation: 'https://d2krrudi3mmzzw.cloudfront.net/v9/?path=/docs/welcome--page',
yeah

2024-02-08 18:34 UTC, alanbsmith commented on modules/docs/mdx/versionsTable.tsx
> +  // version from lerna is a string, so we need to do modify into a number
This comment should be above line 47. `version` is the version from `lerna.json`.

2024-02-08 18:35 UTC, alanbsmith commented on modules/docs/mdx/versionsTable.tsx
> +                <a href={item.documentation} target="_blank">
```suggestion
                <a href={item.documentation} target="_blank" rel="noreferrer">
```

2024-02-08 19:04 UTC, alanbsmith approved these changes

2024-02-08 19:11 UTC, mannycarrera4 commented on modules/docs/mdx/versionsTable.tsx
> +  // version from lerna is a string, so we need to do modify into a number
```suggestion
```

2024-02-08 19:11 UTC, mannycarrera4 commented on modules/docs/mdx/versionsTable.tsx
> +  const currentMajorVersion = Number(version.split('.')[0]);
```suggestion
  // version from lerna is a string, so we need to do modify into a number
  const currentMajorVersion = Number(version.split('.')[0]);
```

2024-02-08 19:40 UTC, merged